// Views/Login/LoginTOTPView.swift
// LoanOS — Borrower App
// Login Step 4 — Minimal authenticator code screen.

import SwiftUI

struct LoginTOTPView: View {
    @Binding var path: NavigationPath
    
    @EnvironmentObject private var viewModel: LoginViewModel
    @EnvironmentObject private var session: SessionStore

    @State private var code = ""
    @FocusState private var focused: Bool

    private var canContinue: Bool {
        code.count == 6
    }

    var body: some View {
        VStack(spacing: 0) {
            topBar
                .padding(.bottom, 22)

            VStack(alignment: .leading, spacing: 22) {
                headerSection
                codeCard
                actionSection

                Spacer()
            }
            .padding(.horizontal, 20)
        }
        .background(
            LinearGradient(
                colors: [Color.white, DS.surface],
                startPoint: .top,
                endPoint: .bottom
            )
            .ignoresSafeArea()
        )
        .navigationBarHidden(true)
        .onAppear {
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
                focused = true
            }
        }
    }

    private var topBar: some View {
        HStack {
            Button {
                if !path.isEmpty {
                    path.removeLast()
                }
            } label: {
                ZStack {
                    Circle()
                        .fill(.white.opacity(0.82))
                        .background(.ultraThinMaterial, in: Circle())

                    Image(systemName: "chevron.left")
                        .font(.system(size: 17, weight: .semibold))
                        .foregroundColor(DS.textPrimary)
                }
                .frame(width: 42, height: 42)
                .shadow(color: .black.opacity(0.04), radius: 10, x: 0, y: 4)
            }

            Spacer()
        }
        .padding(.horizontal, 20)
        .padding(.top, 12)
        .padding(.bottom, 6)
    }

    private var headerSection: some View {
        VStack(alignment: .leading, spacing: 10) {
            Text("Enter authenticator code")
                .font(.system(size: 28, weight: .bold, design: .rounded))
                .foregroundColor(DS.textPrimary)

            Text("Open your authenticator app and enter the current 6-digit code.")
                .font(.system(size: 16))
                .foregroundColor(DS.textSecondary)
                .lineSpacing(3)
        }
    }

    private var codeCard: some View {
        VStack(alignment: .leading, spacing: 18) {
            VStack(alignment: .leading, spacing: 4) {
                Text("Verification code")
                    .font(.system(size: 14, weight: .medium))
                    .foregroundColor(DS.textSecondary)

                Text("Generated by your authenticator app")
                    .font(.system(size: 14))
                    .foregroundColor(DS.textSecondary)
            }

            OTPBoxRow(otp: $code, focused: $focused)
                .disabled(viewModel.isLoading)
        }
        .padding(20)
        .background(.white.opacity(0.84))
        .background(.ultraThinMaterial)
        .clipShape(RoundedRectangle(cornerRadius: 24, style: .continuous))
        .overlay(
            RoundedRectangle(cornerRadius: 24, style: .continuous)
                .stroke(.white.opacity(0.92), lineWidth: 1)
        )
        .shadow(color: .black.opacity(0.04), radius: 14, x: 0, y: 6)
    }

    @State private var isVerifying = false

    private var actionSection: some View {
        VStack(spacing: 16) {
            PrimaryBtn(
                title: (viewModel.isLoading || isVerifying) ? viewModel.loadingActionText : "Verify",
                disabled: !canContinue || viewModel.isLoading || isVerifying
            ) {
                focused = false
                isVerifying = true
                Task {
                    let success = await viewModel.verifyMFA(code: code)
                    if success {
                        if viewModel.requiresPasswordChange {
                            path.append(LoginRoute.passwordChange)
                        } else {
                            AnalyticsManager.shared.logEvent(.loginCompleted)
                            session.completeSession(contactIdentifier: viewModel.currentLoginIdentifier)
                        }
                    }
                    isVerifying = false
                }
            }

            if viewModel.allowedFactors.count > 1 {
                Button {
                    // Navigate back to selection screen by finding its index
                    // Simplest is to pop to root or pop 2 levels. 
                    // Usually, path has: [mfaSelection (maybe), passkey, totp] or [passkey, totp]
                    // If we just remove all until mfaSelection...
                    // Let's just pop the path back to empty, which brings us to LoginStep1, 
                    // or let's pop to mfaSelection. Since path is a NavigationPath, it's opaque.
                    // We can just clear the path, or let the user use the back button.
                    // Actually, since we know mfaSelection is the first route if there are > 1 factors:
                    // we remove until path count is 1.
                    while path.count > 1 {
                        path.removeLast()
                    }
                } label: {
                    Text("Try another method")
                        .font(.system(size: 15, weight: .medium))
                        .foregroundColor(DS.primary)
                }
            }
        }
    }
}
