ALTER TYPE loan_application_status ADD VALUE IF NOT EXISTS 'OFFICER_REVIEW';
ALTER TYPE loan_application_status ADD VALUE IF NOT EXISTS 'OFFICER_APPROVED';
ALTER TYPE loan_application_status ADD VALUE IF NOT EXISTS 'OFFICER_REJECTED';
ALTER TYPE loan_application_status ADD VALUE IF NOT EXISTS 'MANAGER_REVIEW';
ALTER TYPE loan_application_status ADD VALUE IF NOT EXISTS 'MANAGER_APPROVED';
ALTER TYPE loan_application_status ADD VALUE IF NOT EXISTS 'MANAGER_REJECTED';
